InFlix/force-app/main/default/objects/Episode__c/fields/Length_min__c.field-meta.xml
<CustomField>
    <fullName>Length_min__c</fullName>
    <label>Length(min)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

InFlix/force-app/main/default/objects/Episode__c/fields/TV_series__c.field-meta.xml
<CustomField>
    <fullName>TV_series__c</fullName>
    <label>TV series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

InFlix/force-app/main/default/objects/Episode__c/fields/Watched__c.field-meta.xml
<CustomField>
    <fullName>Watched__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Watched</label>
    <type>Checkbox</type>
</CustomField>

InFlix/force-app/main/default/objects/Season__c/fields/Length_min__c.field-meta.xml
<CustomField>
    <fullName>Length_min__c</fullName>
    <label>Length(min)</label>
    <summarizedField>Episode__c.Length_min__c</summarizedField>
    <summaryForeignKey>Episode__c.Season__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

InFlix/force-app/main/default/objects/Season__c/fields/Number_of_episodes__c.field-meta.xml
<CustomField>
    <fullName>Number_of_episodes__c</fullName>
    <label>Number of episodes</label>
    <summaryForeignKey>Episode__c.Season__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

InFlix/force-app/main/default/objects/Season__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

InFlix/force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InFlix/force-app/main/default/objects/TV_Series__c/fields/Length_min__c.field-meta.xml
<CustomField>
    <fullName>Length_min__c</fullName>
    <label>Length(min)</label>
    <summarizedField>Episode__c.Length_min__c</summarizedField>
    <summaryForeignKey>Episode__c.TV_series__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

InFlix/force-app/main/default/objects/TV_Series__c/fields/Number_of_episodes__c.field-meta.xml
<CustomField>
    <fullName>Number_of_episodes__c</fullName>
    <label>Number of episodes</label>
    <summaryForeignKey>Episode__c.TV_series__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

InFlix/force-app/main/default/classes/TVSeriesController.cls
/**
 * @author Aleksandra Fornal <aleksandrafornal@accenture.com>
 * @date 03/04/2024
 * @description This class provides methods for TV series browser and episode details component.
 */
public with sharing class TVSeriesController {
    /**
     * @author Aleksandra Fornal <aleksandrafornal@accenture.com>
     * @date 03/04/2024
     * @description The method returns list of TV series with their title, id and logo.
     *
     * @return List of TV series.
     */
    @AuraEnabled(cacheable=true)
    public static List<TV_Series__c> getAllTVSeries() {
      return [
        SELECT Id, Name, Logo__c
        FROM TV_Series__c
        ORDER BY Name
      ];
    }

    /**
     * @author Aleksandra Fornal <aleksandrafornal@accenture.com>
     * @date 03/04/2024
     * @description The method returns list of seasons from given TV series with their name, id, number 
     * of episodes.
     *
     * @param inTVSeriesId id of chosen TV series.
     * @return List of seasons.
     */
    @AuraEnabled(cacheable=true)
    public static List<Season__c> getAllSeasons(String inTVSeriesId) {
      return [
        SELECT Id, Name, Number_of_episodes__c
        FROM Season__c
        WHERE TV_Series__c = :inTVSeriesId
        ORDER BY Name
      ];
    }

    /**
     * @author Aleksandra Fornal <aleksandrafornal@accenture.com>
     * @date 03/04/2024
     * @description The method returns list of episodes with their name, id, length in minutes.
     *
     * @param inSeasonId id of chosen season.
     * @return List of episodes.
     */
    @AuraEnabled(cacheable=true)
    public static List<Episode__c> getAllEpisodes(String inSeasonId) {
      return [
        SELECT Id, Name, Length_min__c
        FROM Episode__c
        WHERE Season__c = :inSeasonId
        ORDER BY Name
      ];
    }

    /**
     * @author Aleksandra Fornal <aleksandrafornal@accenture.com>
     * @date 03/04/2024
     * @description The method returns episode with its id, name, title, length in minutes, watched,
     * description, TV series logo and trailer.
     *
     * @param inEpisodeId id of chosen episode.
     * @return Episode.
     */
    @AuraEnabled(cacheable=true)
    public static Episode__c getEpisodeDetails(String inEpisodeId) {
      return [
        SELECT
          Id,
          Name,
          Title__c,
          Length_min__c,
          Description__c,
          Watched__c,
          TV_Series__r.Logo__c, 
          TV_Series__r.Trailer__c
        FROM Episode__c
        WHERE Id = :inEpisodeId
      ];
    }
}