InFlix/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InFlix/force-app/main/default/objects/Recipe__c/Recipe__c.object-meta.xml
<CustomObject>
    <label>Recipe</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

InFlix/force-app/main/default/objects/Recipe__c/fields/Diet__c.field-meta.xml
<CustomField>
    <fullName>Diet__c</fullName>
    <label>Diet</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Balanced</fullName>
                <default>true</default>
                <label>Balanced</label>
            </value>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Vegan</fullName>
            </value>
            <value>
                <fullName>Gluten-free</fullName>
            </value>
            <value>
                <fullName>Lactose-free</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InFlix/force-app/main/default/objects/Recipe__c/fields/Ingredients__c.field-meta.xml
<CustomField>
    <fullName>Ingredients__c</fullName>
    <description>Ingredients for the recipe</description>
    <label>Ingredients</label>
    <type>TextArea</type>
</CustomField>

InFlix/force-app/main/default/objects/Recipe__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Recipes</relationshipLabel>
    <relationshipName>Recipes</relationshipName>
    <type>Lookup</type>
</CustomField>

InFlix/force-app/main/default/objects/Recipe__c/fields/Preparation__c.field-meta.xml
<CustomField>
    <fullName>Preparation__c</fullName>
    <label>Preparation</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

InFlix/force-app/main/default/objects/Recipe__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>Recipes</relationshipLabel>
    <relationshipName>Recipes</relationshipName>
    <type>Lookup</type>
</CustomField>

InFlix/force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InFlix/force-app/main/default/classes/RecipesController.cls
/**
 * @author Aleksandra Fornal <aleksandrafornal@accenture.com>
 * @date 03/04/2024
 * @description This class provides methods for Recipe browser and details component.
 */
public class RecipesController {
    /**
     * @author Aleksandra Fornal <aleksandrafornal@accenture.com>
     * @date 06/04/2024
     * @description The method returns list of recipes related to selected TV series.
     *
     * @param inTVSeriesId id of related TV series.
     * @return List of recipes.
     */
    @AuraEnabled(cacheable=true)
    public static List<Recipe__c> getAllRecipesRelatedToTVSeries(String inTVSeriesId) {
      return [
        SELECT Id, Name, Photo__c
        FROM Recipe__c
        WHERE TV_Series__c = :inTVSeriesId
        ORDER BY Name
      ];
    }

    /**
     * @author Aleksandra Fornal <aleksandrafornal@accenture.com>
     * @date 06/04/2024
     * @description The method returns list of recipes related to selected movie.
     *
     * @param inMovieId id of related movie.
     * @return List of recipes.
     */
    @AuraEnabled(cacheable=true)
    public static List<Recipe__c> getAllRecipesRelatedToMovie(String inMovieId) {
      return [
        SELECT Id, Name, Photo__c
        FROM Recipe__c
        WHERE Movie__c = :inMovieId
        ORDER BY Name
      ];
    }

    /**
     * @author Aleksandra Fornal <aleksandrafornal@accenture.com>
     * @date 06/04/2024
     * @description The method returns recipe with its id, name, diet, ingredients and preparation.
     *
     * @param inRecipeId id of chosen recipe.
     * @return Recipe.
     */
    @AuraEnabled(cacheable=true)
    public static Recipe__c getRecipeDetails(String inRecipeId) {
      return [
        SELECT
          Id,
          Name,
          Diet__c,
          Ingredients__c,
          Preparation__c,
          Photo__c
        FROM Recipe__c
        WHERE Id = :inRecipeId
      ];
    }
}